### ISSUE TITLE
PS2classics support?

### ISSUE THREAD

**Issue by Arthandas** [has207/psxtract-2#14]
Hello, any chances of adding support for PS2classics?

**Comment by Arthandas** [comment]
Actually, disregard that, there are already tools capable of doing that. On the other hand, PSP eboot.pbp support would be nice.

**Comment by mokMan23** [comment]
PS3 & PSP EBOOT.PBP files are the exact same.
Use [Apollo Save tool](https://github.com/bucanero/apollo-ps3/releases/latest) to decrypt PS2 Classics, and [remove the LIMG sector](https://www.psx-place.com/threads/what-is-the-ps2-limg-sector.24626/#post-185823) for a Redump verified ISO.

**Comment by Arthandas** [comment]
> PS3 & PSP EBOOT.PBP files are the exact same.
That may be the case, but psxtract-2 can't make a Redump verified ISO from a PSP EBOOT.

> Use [Apollo Save tool](https://github.com/bucanero/apollo-ps3/releases/latest) to decrypt PS2 Classics, and [remove the LIMG sector](https://www.psx-place.com/threads/what-is-the-ps2-limg-sector.24626/#post-185823) for a Redump verified ISO.

Yeah, I figured it out. I'm using ps2classic.exe from the [PS3 Tools Collection v4.8.1](https://www.psx-place.com/resources/ps3-tools-collection.594/)

**Comment by has207** [comment]
Right, there's no such things as PSP eboots, they're the same thing. If a particular one is not redump verifiable that's an issue with that particular eboot not the fact that you downloaded it from a PSP

**Comment by Arthandas** [comment]
If they're the same thing, why psxtract-2 can't make an iso from a psp eboot?

**Comment by has207** [comment]
> If they're the same thing, why psxtract-2 can't make an iso from a psp eboot?

What eboot and how did you obtain this eboot? if you download from psn then it should be the same. if you found somewhere online then it's likely a custom one not made by Sony and isn't going to be supported by this tool

**Comment by Arthandas** [comment]
Eboot extracted from a pkg obtained directly from PSN. I've tried two of them: Castlevania Dracula X Chronicles (EU) and Gungnir (US). Both end with:

`Unpacking PBP EBOOT.PBP...
[0]        604 bytes | PARAM.SFO
[1]      30202 bytes | ICON0.PNG
[2]          0 bytes | ICON1.PMF
[3]      44130 bytes | PIC0.PNG
[4]     148979 bytes | PIC1.PNG
[5]          0 bytes | SND0.AT3
[6]      14893 bytes | DATA.PSP
[7]  149473472 bytes | DATA.PSAR
Successfully unpacked EBOOT.PBP!

ERROR: Not a valid ISO image!`

**Comment by has207** [comment]
There's a tool out there for PSP games:

https://www.gamebrew.org/wiki/PSN_PKG_Decryptor_and_Extractor_PSP

This tool is for PS1 games.
