### ISSUE TITLE
Resident Evil 1 and 2 not playable on Duckstation

### ISSUE THREAD

**Issue by tydog98** [has207/psxtract-2#16]
Duckstation does not find the generated bin/cue files

**Comment by has207** [comment]
You're going to have to provide a bit more detail here, I have RE2 and it works just fine. What's the output you get when you run the tool?

**Comment by tydog98** [comment]
Apparently it was just a WINE issue. Going on actual Windows fixed the problem. RE1 would give an error with the ATRAC3 stuff. RE2 still does but also produces a usable ROM

**Comment by rumblerosesxx** [comment]
RE2 is a known issue with the eboot, it's mentioned in the README on the front page of this repo. The audio tracks are empty on the real disc and not included at all in the eboot although the eboot thinks they should be. In any case it does work yes

**Comment by has207** [comment]
RE2 is a known issue with the eboot, it's mentioned in the README on the front page of this repo. The audio tracks are empty on the real disc and not included at all in the eboot although the eboot thinks they should be. In any case it does work yes
