### ISSUE TITLE
Dino Crisis (SLUS-00922) - Redump Checksum Mismatch

### ISSUE THREAD

**Issue by tjmatthews1999** [has207/psxtract-2#5]
Hi, I wanted to start by saying I've used psxtract a number of times, so it is very exciting to see this project actively being worked on again with multi-track support.

One of the games I had been holding off on extracting in the past is Dino Crisis. From what I can tell, I believe the Sony PSClassics version is using the original version ([http://redump.org/disc/459/](http://redump.org/disc/459/)) and NOT the Greatest Hits revision ([http://redump.org/disc/473/](http://redump.org/disc/473/)). For what it's worth, similar to the example of Resident Evil 2: Dualshock Edition that I have seen mentioned, this game (and Dino Crisis 2 for that matter) contains an empty audio track (maybe it's a Capcom quirk?). When extracting, even though the size of the main data track (DATA TRACK.BIN.ISO) is correct (379984416 bytes), the checksum mismatches with Redump.

DATA TRACK.BIN.ISO MD5: 26DFB88760946B17552A89C2F4DDCE90
Redump data track MD5: 4990BB2A9E3374A234885AC983A9397A

At this point, I can't tell if this is a bug or maybe just some kind of quirk. I've attached the entire run log below:

PS BASE_PATH> .\psxtract-2\psxtract-2\psxtract.exe .\SLUS00922\EBOOT.PBP
Unpacking PBP .\SLUS00922\EBOOT.PBP...
[0]        944 bytes | PARAM.SFO
[1]      10918 bytes | ICON0.PNG
[2]          0 bytes | ICON1.PMF
[3]      40636 bytes | PIC0.PNG
[4]       2651 bytes | PIC1.PNG
[5]          0 bytes | SND0.AT3
[6]      10347 bytes | DATA.PSP
[7]  254279029 bytes | DATA.PSAR
Successfully unpacked .\SLUS00922\EBOOT.PBP!

Single disc game detected!

Found STARTDAT offset: 0x0f27bdd0
Saving STARTDAT as STARTDAT.BIN...

Decrypting ISO header...
ISO header successfully decrypted! Saving as ISO_HEADER_0.BIN...

ISO disc: SLUS_00922
ISO title: Dino Crisis®

Found special data offset: 0x0f27edc5
Decrypting special data...
Special data successfully decrypted! Saving as SPECIAL_DATA.BIN...

Offset 35m:56s:8f at 0428
Offset 39m:28s:8f at 0414
seeking to 100000 + ee2bcd0 (ef2bcd0)
Extracting audio track 2 (15900 sectors, 3474048 bytes)
1 audio tracks extracted to ATRAC3
Attempting to convert from ATRAC3 to WAV, this may take awhile...

BASE_PATH\psxtract-2\psxtract-2\at3tool.exe -d "D01 TRACK02.AT3" "D01 TRACK02.WAV"
Decoding 132 kbps (ATRAC3)
Decoded Bytes    = 3473664 Bytes@9046frames(ave=384bytes)

1 audio tracks converted to WAV
Need to pad 348756 bytes
1 audio tracks converted to BIN

Building the data track...
ISO offset 100000
......................................................................................................
Read ee2bcd0 bytes, wrote 16aba100 bytes
Data track successfully reconstructed! Saving as ISO.BIN...

Offset 0m:0s:0f at 041e
Offset 35m:56s:8f at 0428
Converting the final image to BIN/CUE...
Patching ECC/EDC data...
Processing 161558 sectors
The image has been fixed!

Generating CUE file...
        adding DATA TRACK.BIN.ISO
        adding D01 TRACK02.BIN
Disc successfully converted to BIN/CUE format!

**Comment by has207** [comment]
Looks like this is another game with some weird ECC data in last sector on physical disc, marking as dup of #3
