### ISSUE TITLE
"Corrupt CD-ROM XA subheader" warnings with Mega Man games

### ISSUE THREAD

**Issue by mokMan23** [has207/psxtract-2#8]
Using a Windows 7 (latest version of Windows I own) VM, with C++ 2022 (I can't get AT3 conversion working with Wine), I get the warning below:
`Corrupt CD-ROM XA subheader will be copied to the output file. Channel number mismatch at [timestamp]: [offset0] vs [offset1]`
The ROMs are still fully playable in DuckStation, Misadventures of Tron Bonne outputs a few warnings, while Mega Man Legends outputs over 1500. For some reason, it's only for these games, hence the name of the issue. I'll include the offsets for both games, & more if I, or others find them:
- Misadventures of Tron Bonne: `0x00, 0x80`
- Mega Man Legends: `0x02, 0x82`

**Comment by has207** [comment]
These warnings are not errors, they don't indicate anything is wrong, just debugging info hence I just suppress them for the most part.

I can verify that Tron Bonne is extracted fine minus that mysterious watermark at the end of the disc, it should play fine on either emulator or burned to disc without it. But I'll be adding patches to fix these images at some point to get rid of the hash mismatches.

I don't own the MM legends 1 or 2 eboots but checking the iso dumps it seems they both have the same watermark so pxtract won't be able to reproduce them until I add game specific patches.
